
export const FETCH_COFFEE_LIST = 'FETCH_COFFEE_LIST';
export const FETCH_COFFEE_DETAILS = 'FETCH_COFFEE_DETAILS';

export const SWITCH_COLOR="SWITCH_COLOR";
export const OPEN_MODAL="OPEN_MODAL";
export const CLOSE_MODAL="CLOSE_MODAL";
